# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Alicia Tee
description: My website
url: "http://aliciateerl.github.io/site"
twitter_username:
default_img:

# Profile settings
name: Alicia Tee
profile_img:
profile:
social:
  github: http://github.com/
  instagram: https://www.instagram.com/aliciateerl/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
